#!/bin/bash
source utils
load_conf
decode_qs

set -x

declare -A initiator_iqns
parse_initiator_iqn_list "${request[initiator_iqns]}" initiator_iqns
if ! (( ${#initiator_iqns[@]} )); then
    http_400 "no initiator iqn specified"
fi

src_iqn="${request[target_iqn]}"
if ! iqn_validate "$src_iqn"; then
    http_400 "invalid target iqn: \"$src_iqn\""
fi

src_image_id="${src_iqn##*.}"
if ! image_clone id "$src_image_id"; then
    http_500 "failed to clone \"$src_iqn\""
fi

image_set_initiator_iqns $id "${!initiator_iqns[@]}"

image_share "$id" target_iqn "${!initiator_iqns[@]}"

http_nocache "$target_iqn"
