#!/bin/bash
source utils
load_conf
decode_qs

if ! [[ "${request[size]}" =~ [0-9]+[bBkKmMgGtT]? ]]; then
    echo 'HTTP/1.0 400'
    echo 'Content-type: text/plain'
    echo 
    echo invalid size argument: \"${request[size]}\"
    exit 1
fi

if ! iqn_validate "${request[initiator_iqn]}"; then
    echo 'HTTP/1.0 400'
    echo 'Content-type: text/plain'
    echo 
    echo invalid initiator iqn: \"${request[initiator_iqn]}\"
    exit 1
fi

id=$(uuidgen)
id=${id##*-}
if ! zfs create -s -V ${request[size]} $IMAGES_DATASET/$id >/dev/null; then
    echo 'HTTP/1.0 500'
    echo 'Content-type: text/plain'
    echo 
    echo 500 failed to allocate image
    exit 1
fi

set -x

target_iqn="iqn.2016-05.com.deepin:images.${id}"
targetcli /backstores/iblock                create "$target_iqn" /dev/zvol/"$IMAGES_DATASET"/"$id"
targetcli /iscsi/                           create "$target_iqn"
targetcli /iscsi/"$target_iqn"/tpg1/        set attribute authentication=0
targetcli /iscsi/"$target_iqn"/tpg1/        set attribute demo_mode_write_protect=0
targetcli /iscsi/"$target_iqn"/tpg1/luns    create /backstores/iblock/"$target_iqn"
targetcli /iscsi/"$target_iqn"/tpg1/acls    create "${request[initiator_iqn]}"
targetcli /iscsi/"$target_iqn"/tpg1/portals create

echo 'Content-type: text/plain'
echo 'Cache-Control: no-cache, no-store, must-revalidate'
echo 'Pragma: no-cache'
echo 'Expires: 0'
echo
echo "$target_iqn"
