#!/bin/bash
source utils
load_conf
decode_qs

set -x

if ! [[ "${request[size]}" =~ [0-9]+[bBkKmMgGtT]? ]]; then
    http_400 "invalid size argument: \"${request[size]}\""
fi

declare -A initiator_iqns
parse_initiator_iqn_list "${request[initiator_iqns]}" initiator_iqns
if ! (( ${#initiator_iqns[@]} )); then
    http_400 "no initiator iqn specified"
fi

if ! image_create id ${request[size]}; then
    http_500 failed to allocate image
fi

image_set_initiator_iqns $id "${!initiator_iqns[@]}"

image_share "$id" target_iqn "${!initiator_iqns[@]}"

http_nocache "$target_iqn"
