#!/bin/bash
load_conf()
{
    source /etc/zfs-gate.conf
}

decode_qs()
{
    declare -Ag request
    for _tmp in ${QUERY_STRING//&/ }; do
        eval request[\"${_tmp%=*}\"]=\"$(busybox httpd -d "${_tmp#*=}")\"
    done
}

dataset_exists()
{
    zfs list "$1" &>/dev/null
}

# https://gist.github.com/cdown/1163649
# urlencode <string>
urlencode() {
    old_lc_collate=$LC_COLLATE
    LC_COLLATE=C
    
    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%%%02X' "'$c" ;;
        esac
    done
    
    LC_COLLATE=$old_lc_collate
}

# matches iqn in form below
# * iqn.1993-08.org.debian:deepin.15.1.amd64
# * iqn.1993-08.org.debian:01:d4acd8b86f
iqn_validate()
{
    [[ $1 =~ ^iqn\.[0-9]{4}-[0-9]{2}(\.[a-zA-Z0-9_]+){2}(:[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)*)+$ ]]
}

# target_iqn image_dataset initiator_iqn1 ... initiator_iqnN
iscsi_share()
{
    targetcli /backstores/iblock create "$1" "$2"
    targetcli /iscsi/ create "$1"
    targetcli /iscsi/"$1"/tpg1/ set attribute authentication=0
    targetcli /iscsi/"$1"/tpg1/ set attribute demo_mode_write_protect=0
    targetcli /iscsi/"$1"/tpg1/luns create /backstores/iblock/"$1"
    targetcli /iscsi/"$1"/tpg1/portals create

    local _tmp
    for _tmp in "${@:3}"; do
        targetcli /iscsi/"$1"/tpg1/acls create "$_tmp"
    done
}

iscsi_is_shared()
{
    [[ -d "/sys/kernel/config/target/iscsi/$1" ]]
}

# target_iqn
iscsi_unshare()
{
    targetcli /backstores/iblock delete "$1"
    targetcli /iscsi/ delete "$1"
}

# var_name
image_id_gen()
{
    eval $1=\"$(uuidgen)\"
    eval $1=\"${!1##*-}\"
}

# image_id_var_name src_image_id
image_clone()
{
    image_id_gen $1
    zfs clone "$IMAGES_DATASET/$2@freeze" "$IMAGES_DATASET/${!1}"
}

# image_id_var_name size
image_create()
{
    image_id_gen $1
    zfs create -s -V $2 "$IMAGES_DATASET/${!1}" >/dev/null
}

# image_id
image_is_frozen()
{
    zfs list "$IMAGES_DATASET/$1@freeze" &>/dev/null
}

# image_id
image_freeze()
{
    image_is_frozen "$1" && return

    zfs snapshot "$IMAGES_DATASET/$1@freeze"
}

# initiator_iqns_var_name image_id
image_get_initiator_iqns()
{
    local -i _i
    local _iqn
    for (( _i=1; ; _i++ )); do
        _iqn=$(zfs get zfs-gate:initiaor-iqn$_i -H -o value $IMAGES_DATASET/$2 2>/dev/null)
        [[ '-' == "$_iqn" ]] && break
        eval $1+=\($_iqn\)
    done
}

# image_id iqn1 .. iqnN
image_set_initiator_iqns()
{
    while (( 1 < $# )); do
        zfs set zfs-gate:initiaor-iqn$(($#-1))="${@:$#:1}" $IMAGES_DATASET/$1
        set -- "${@:1:$#-1}"
    done
}

# target_iqn_var_name image_id [initiator-iqn1 .. initiator-iqnN]
image_share()
{
    eval $1="$TARGET_IQN_PREFIX.$2"
    if [[ -d "/sys/kernel/config/target/iscsi/${!1}" ]]; then
        return
    fi

    local -a _iqns
    if (( $# > 2 )); then
        _iqns=(${@:3})
    else
        image_get_initiator_iqns _iqns $2
    fi
    iscsi_share "${!1}" "/dev/zvol/$IMAGES_DATASET/$2" "${_iqns[@]}"
}

image_is_shared()
{
    iscsi_is_shared "$TARGET_IQN_PREFIX.$2"
}

image_share_all()
{
    local _var_no_use
    image_foreach 'image_share _var_no_use'
}

# image_id
image_unshare()
{
    local _target_iqn="$TARGET_IQN_PREFIX.$1"
    if [[ ! -d "/sys/kernel/config/target/iscsi/$_target_iqn" ]]; then
        return
    fi

    iscsi_unshare "$_target_iqn"
}

# image_id
image_unshare_all()
{
    image_foreach image_unshare
}

# status mimetype message...
http_response()
{
    echo "HTTP/1.0 $1"
    echo "Content-type: $2"
    echo 
    echo -e "${@:3}"
    exit
}

http_400()
{
    http_response 400 "text/plain" "$@"
}

http_500()
{
    http_response 500 "text/plain" "$@"
}

http_nocache()
{
    echo 'Content-type: text/plain'
    echo 'Cache-Control: no-cache, no-store, must-revalidate'
    echo 'Pragma: no-cache'
    echo 'Expires: 0'
    echo
    echo -e "$@"
}

# initiator_iqns_var_name initiator_iqn_list
# initiator_iqn_list: a list of iqn separated by ,
# initiator_iqns_var_name: name of a variable which type is associatve array
parse_initiator_iqn_list()
{
    local -i _tmp
    for _iqn in ${2//,/ }; do
        if ! iqn_validate "$_iqn"; then
            http_400 "invalid initiator iqn: \"$_iqn\""
        fi
    
        eval $1[\"$_iqn\"]=""
    done
}

# cb [cb_arg1 .. cb_argN]
# cb: callback command
# [cb_arg1 .. cb_argN]: arguments being passed to cb
image_foreach()
{
    local _tmp
    while read _tmp; do
        _tmp="${_tmp#$IMAGES_DATASET}"
        _tmp="${_tmp#/}"
        [[ -z "$_tmp" ]] && continue
        eval $1 \"$_tmp\" \"\${@:2}\"
    done < <(zfs list -r -H -o name "$IMAGES_DATASET" 2>/dev/null)
}

# image_id_var_name iqn
iqn_to_image_id()
{
    eval $1=\"${2##*.}\"
}

# dataset_var_name iqn
iqn_to_dataset()
{
    eval $1=\"$IMAGES_DATASET/${2##*.}\"
}

# iqn_var_name image_id
image_id_to_iqn()
{
    eval $1=\"$TARGET_IQN_PREFIX.$2\"
}

# iqn_var_name dataset
dataset_to_iqn()
{
    image_id_to_iqn "$1" "${2#$IMAGES_DATASET/}"
}

set -e
PS4="> ${0##*/}: "
set -x

load_conf
