#!/bin/bash
source ../lib/utils
load_conf

while read line; do
    cols=($line)
    [[ "$IMAGES_DATASET" == "${cols[0]}" ]] && continue
    dataset_to_iqn "cols[0]" "${cols[0]}"
    result+="${cols[@]}\n"
done < <(zfs list -H -o name,volsize,used -r $IMAGES_DATASET)

http_nocache "$result"
