#!/bin/bash
source ../lib/utils
load_conf
decode_qs

set -x

target_iqn="${request[target_iqn]}"
if [[ -z "$target_iqn" ]]; then
    http_400 no target iqn specified
fi

if ! iqn_validate "$target_iqn"; then
    http_400 invalid target iqn: $target_iqn
fi

iqn_to_image_id id "$target_iqn"
if ! image_freeze $id; then
    http_500 failed to freeze image
fi

http_nocache
